### ISSUE TITLE
problem with permissions

### ISSUE THREAD

**Issue by gut4** [cdata/collapsify#1]
Hello! I install mobilize by `npm install -g mobilize` without sudo, but have `sudo chown -R $USER /usr/local`
And get this error:

```
Error in unix_dgram bind of /usr/local/bin/cluster.8410.server.sock
Error: EACCES, Permission denied
    at startListening (/usr/local/lib/node_modules/mobilize/node_modules/cluster/lib/master.js:794:9)
    at Master.startListening (/usr/local/lib/node_modules/mobilize/node_modules/cluster/lib/master.js:787:5)
    at Master.<anonymous> (/usr/local/lib/node_modules/mobilize/node_modules/cluster/lib/master.js:296:12)
    at Master.emit (events.js:81:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mobilize/node_modules/cluster/lib/master.js:329:10)
    at Socket.emit (events.js:61:17)
    at dgram.js:127:16
Error: EACCES, Permission denied
    at startListening (/usr/local/lib/node_modules/mobilize/node_modules/cluster/lib/master.js:794:9)
    at Master.startListening (/usr/local/lib/node_modules/mobilize/node_modules/cluster/lib/master.js:787:5)
    at Master.<anonymous> (/usr/local/lib/node_modules/mobilize/node_modules/cluster/lib/master.js:296:12)
    at Master.emit (events.js:81:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mobilize/node_modules/cluster/lib/master.js:329:10)
    at Socket.emit (events.js:61:17)
    at dgram.js:127:16
```

**Comment by cdata** [comment]
Hey, thanks for the tip! Looking into it.

**Comment by cdata** [comment]
Hey, so after setting up my environment as you described, I realised the problem is simple: by default, the server tries to run on port 80, which requires sudo or root permissions. If you use the --port flag and set the port to something like 8080, you should be able to run mobilize without heightened permissions.
